#+title: M1 Writeup
#+author: 



#+startup: showeverything

#+latex_header: \usepackage{amsmath,amssymb,fullpage,dsfont,setspace}
#+latex_header: \newcommand{\bs}{\boldsymbol}
#+latex_header: \newcommand{\attn}[1]{\textbf{***{#1}***}}
#+latex_header: \newcommand{\src}{\attn{source}}
#+latex_header: \setlength{\parskip}{\baselineskip}
#+latex_header: \newcommand{\logit}{\text{logit}}

#+latex_header: \setstretch{1.5}

* Checklist							   :noexport:
** Notation
   - [ ] Locations
     - [ ] Coordinates
     - [ ] Covariates
     - [ ] Neighbors
   - [ ] Dynamics model
     - [ ] Gravity model
** Spread dynamics models
   - [ ] $1 - \Pi_{i}[ 1 - P_{i,j}]$
   - [ ] Gravity model
   - [ ] Gravity model with time infected
   - [ ] Range model
   - [ ] Cave model
   - [ ] Setting generative model parameters
** Structure generation
   - [X] Covariates
   - [ ] Network distance
   - [-] Structures
     - [X] Alley
     - [ ] Bowtie
     - [ ] Grid
     - [X] Random
     - [ ] Ring
     - [ ] Scalefree
** Simulation details
   - [ ] Start settings
   - [ ] Significant points
     - [ ] Model estimation
     - [ ] Strategy estimation
   - [ ] Number of time points
   - [ ] Objective function
   - [ ] Optimization online tuning
   - [ ] Model estimation
** Priority scores
   - [ ] Form of the scores
   - [ ] Selection process
   - [ ] Features
** M1 Optimization
   - [ ] Runners
   - [ ] SGD
** Competing policies
   - [ ] Proximal
   - [ ] Myopic


# begin document

* Notation

* System dynamics model

** Gravity model

To model the evolution of the disease, we model the probability that
an infected location $i$ infects an uninfected location $j$ at time
point $t$.  We denote this probability as $p_{i,j,t}$.  If we assume
independence across events $i$ infecting $j$ and $i'$ infecting $j$,
the probability of $j$ becoming infected at time $t$ is
#+BEGIN_LaTeX
  \begin{equation*}
    P(X_{j,t} = 1 | X_{\cdot,t}) = X_{j,t-1} \bigvee \left[1 - \prod_{i:
    X_{i,t-1} = 1} ( 1 - p_{i,j,t} ) \right].
  \end{equation*}
#+END_LaTeX

To define $p_{i,j,t}$ we use a form of the gravity model.
#+BEGIN_LaTeX
  \begin{equation*}
    \logit \; p_{i,j,t} = \beta_0 + \beta_1 U_j 
    - \alpha \frac{d_{i,j}}{(c_ic_j)^\nu} - \eta g(\tau_{i,t})
    - \rho A_{j,t-1} - \gamma A_{i,t-1}
  \end{equation*}
#+END_LaTeX
where $\tau_{i,t} = \sum_{t' = 0}^t X_{i,t'}$ is the number of time
points $i$ has been infected.  We compare different forms of
$g(\cdot)$ discussed later.

For model estimation, we use a Bayesian framework.  The priors on the
parameters are as follows $\beta_0 \sim N(0,100)$, $\beta_1 \sim
N(0,10)$, $\log(\alpha) \sim N(0,1)$, $\log(\nu) \sim N(0,1)$, $\rho
\sim N(0,1)$, $\gamma \sim N(0,1)$.


** Model fit diagnostics

When estimating the posterior distributions, we compared multiple
forms for $g(\cdot)$.
#+BEGIN_LaTeX
  \begin{itemize}
    \item $g_j(x) = 0$
    \item $g_j(x) = x - 1$
    \item $g_j(x) = exp(x - 1) - 1$
    \item $g_j(x) = exp(\frac{\max_k c_k+1}{c_j + 1}(x - 1)) - 1$
  \end{itemize}
#+END_LaTeX


* Structure generation

** Structures

*** Random Network

The random network generates location coordinates uniformly on $[0,1]
\times [0,1]$.  Let $C$ denote the set of coordinate pairs.  For any
$i \in \lbrace 1,...,n \rbrace$, $C_{i} \in [0,1] \times [0,1]$.

Let $A$ be the $n \times n$ adjacency matrix where $A_{i,j} = 1$ if
locations $i$ and $j$ are adjacent and $A_{i,j} = 0$ otherwise.  To
determine which locations are connected, we must first define some
notation.  Let $E_{i,j} = \|C_{i} - C_{j}\|_2$ and $E_{i,[j]}$ denote
the $j^{th}$ largest norm excluding $E_{i,i}$ which is zero.  The set
of $k$ nearby locations to location $i$ is $N^{(k)}_i = \lbrace j :
E_{i,j} <= E_{i,[k]} \rbrace$.  Now, the adjacency matrix is defined
as $A_{i,j} = 1$ if $i \in N_{j}^{(k)}$ or $j \in N_{i}^{(k)}$.


#+caption: A random network with 50 locations
#+name: fig:rand25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/randSample.pdf]]



*** Starred Alley

The starred alleyway was produced to incorporate the importance of
network centrality metrics.  An example of a starred alleyway can be
found in figure [[fig:alley25]].  By looking at the structure, the goal is
to identify the locations along the main horizontal line.  If these
locations are treated, it helps to contain the spread of the disease.

Distances between nodes are not defined in the usual way.  For any
node on the outer points, the distance to the closest node on the main
horizontal line is $0.9$ instead of $1.0$.

For a starred alley of size $N$, define
#+BEGIN_LaTeX
  \begin{equation*}
    m_N = \underset{m > 0}{\arg\max} \; f(m) \mathds{1}_{\lbrace f(m) \le N
      \rbrace }
  \end{equation*}
#+END_LaTeX
where
# #+BEGIN_LaTeX
#   \begin{equation*}
#     f(m) = m + \left\lceil \frac{m}{2}
#     \right\rceil 
#     \left(\left\lceil \frac{m}{2} \right\rceil - 1\right) 
#     + (2 - (m \text{ mod } 2)) \left\lceil{\frac{m}{2}\right\rceil.
#     \end{equation*}
# #+END_LaTeX
# or simplified, it becomes
#+BEGIN_LaTeX
  \begin{equation*}
    f(m) = m + \left\lceil \frac{m}{2}
    \right\rceil 
    \left(\left\lceil \frac{m}{2} \right\rceil
      - (m \text{ mod } 2) + 1 \right).
  \end{equation*}
#+END_LaTeX

Let locations $1,\ldots,m_N$ index the locations on the main
horizontal line.  Next define disjoint sets of locations
$\mathcal{N}_i$ for $i = 1,\ldots,m_N$.  The cardinality for
$\mathcal{N}_i$ is defined as
#+BEGIN_LaTeX
  \begin{equation*}
    | \mathcal{N}_i | = \left\lfloor \frac{i}{2} \right\rfloor +
    \mathds{1}_{\lbrace(m_N - i) < (N - f(m_N))\rbrace}.
  \end{equation*}
#+END_LaTeX
For each location $j \in \mathcal{N}_i$ set $A_{i,j} = A_{j,i} = 1$.

To define the coordinates for each location, first set $C_{i} =
\lbrace i,0 \rbrace$ for $i = 1,\ldots,m_N$.  Then for each 


#+caption: The starred alleyway network with 50 locations
#+name: fig:alley25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/alleySample.pdf]]



*** Ring

The ring is a simple circle of locations with a concetrated group in one
section.  To form the ring, place the locations evenly on the circle
then between one pair of locations insert more locations evenly.  An
example can be seen in figure [[fig:ring25]].

Divide the number of locations $N$ into two groups.  Define $N_1 = N -
N_2$ where $N_2 = \lceil N*0.05 \rceil$.  Let $\theta = 2\pi/(N_1+1)$
and $r = 1/(2\sin(\theta/2))$.  Place location $1$ at $C_1 = \lbrace
0,r \rbrace$.  Given location $i-1$ at $C_{i-1}$, place location $i$
at $C_i = rot(\theta) C_{i-1}$ for $i = 2,\ldots,N_1$ and
#+BEGIN_LaTeX
  \begin{equation*}
    rot(\theta) = \left[
      \begin{matrix}
        \cos(\theta) & -\sin(\theta)\\
        \sin(\theta) & \cos(\theta)
      \end{matrix}
    \right]
  \end{equation*}
#+END_LaTeX
Note that $C_{1} \cdot C_{N_1} = \|C_{1}\| \|C_{N_1}\| \cos(2\theta)$.

With the first $N_1$ locations defined, we need to define the last
$N_2$ locations.  Place location $N_1 + i$ at $C_{N_1 + i} =
rot(\theta/N_2)C_{N_1 + i - 1}$ for $i = 1,\ldots,N_2$.  Note that
$C_{N} \cdot C_{N_1} = \|C_{N}\| \|C_{N_1}\| \cos(\theta)$ and $C_{1}
\cdot C_{N} = \|C_{1}\| \|C_{N}\| \cos(\theta)$.

To define the adjacency matrix, $A_{i,i+1} = A_{i+1,i} = 1$ for $i =
1,\ldots,N-1$ and $A_{1,N} = A_{N,1} = 1$.



#+caption: The ring network with 50 locations
#+name: fig:ring25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/ringSample.pdf]]




*** Grid

The grid is a checkerboard-like structure.  First define $N_1$ to be
the number of columns and $N_2$ to be the number of rows.  These
values are defined by
#+BEGIN_LaTeX
  \begin{equation*}
    \lbrace N_1, N_2 \rbrace = \underset{
      \begin{subarray}{c}
        N_1,N_2 > 0\\
        N_1N_2 = N\\
        N_1 \le N_2
      \end{subarray}
    }{\arg\min} \quad |N_1 - N_2|
  \end{equation*}
#+END_LaTeX

Location $i$ is positioned at $C_i = \lbrace (i \text{ mod } N_2), \lfloor
i/N_2 \rfloor \rbrace$.  The adjacency matrix is defined as $A_{i,j} =
1$ if $\|C_i - C_j\| = 1$.

#+caption: The grid network with 50 locations
#+name: fig:grid25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/gridSample.pdf]]



*** Bowtie

The bowtie combines two grid networks with a random network in
between.  Spread of the disease begins in one grid and travels through
the random network and into the other grid.

For a bowtie network of size $N$, create one random network of size
$N_R = \lceil 0.1 N \rceil + ((N - \lceil 0.1 N \rceil) \text{ mod }
2)$ and two grid networks of size $N_G = (N - N_R)/2$.

Let $i_{R}$ be the $i^{th}$ location in the random network and
$i_{G_j}$ be the $i^{th}$ location in the $j^{th}$ grid.n

To connect the three networks, we need to first identify which nodes
in each network will connect to one of the other two networks.  We
will begin with the first grid.  First, define $N_1$ and $N_2$ to be
defined in the same way as in the grid description.  Both grid
networks are the same size, we do not need to distinguish between the
two.  Let $M_{G} = \lceil N_2/3 \rceil$ be the number of points to
connect from the grid networks.  Define the following four sets of locations
#+BEGIN_LaTeX
  \begin{equation*}
    \begin{array}{rcl}
      \Lambda_{G_1} & = & \lbrace N_G -
                          2N_1M_G + kN_1 : k = 1,\ldots,M_G\rbrace\\
      \Lambda_{G_2} & = & \lbrace N_G -
                          2N_1M_G + 1 + (k-1)N_1 : k =
                          1,\ldots,M_G\rbrace\\
      \Lambda_{R_1} & = & \lbrace i : C_{i,1} \le C_{[M_R],1} \rbrace\\
      \Lambda_{R_2} & = & \lbrace i : C_{i,1} \ge C_{[N_R - M_R + 1],1} \rbrace
    \end{array}
  \end{equation*}
#+END_LaTeX
where $[\cdot]$ denotes the usual order statistics.

To define the adjacency matrix, combine the adjacency matrices from
the three separate networks as a block diagonal matrix.  To define the
additional edges, set $A_{i_{G_1},j_R} = A_{j_R,i_{G_1}} = 1$ for all
$i \in \Lambda_{G_1}$ and $j \in \Lambda_{R_1}$ to connect the first
grid to the random network.  Then set $A_{i_{G_2},j_R} =
A_{j_R,i_{G_2}} = 1$ for all $i \in \Lambda_{G_2}$ and $j \in
\Lambda_{R_2}$ to connect the second grid to the random network.

Now that the adjacency marix is defined, we need to finish the
network.  The last step is scaling and adjusting the coordinates from
the three networks.  We define this as an ordered list of operations.
#+BEGIN_LaTeX
  \begin{enumerate}
    \item For $i=1,\ldots,N_R$: $C_{i_{R}} = C_{i_{R}}/2$.
    \item Define $S = (\max_i C_{i_{R},1} - \min_i C_{i_{R},1})/2$.
    \item For $i=1,\ldots,N_R$: $C_{i_{R},1} = C_{i_{R},1} -
    \min_j C_{j_{R},1} + \max_j C_{j_{G_1},1} + S$
    \item For $i=1,\ldots,N_G$:
    $C_{i_{G_2},1} = C_{i_{G_2},1} - \min_j C_{j_{G_2},1} + \max_j
    C_{j_{R},1} + S$.
  \end{enumerate}
#+END_LaTeX


#+caption: The bowtie network with 50 locations
#+name: fig:bowtie25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/bowtieSample.pdf]]


*** Scalefree

The scalefree network is designed so that some locations are highly
connected while others are only connected by a couple edges.  This
type of network was originally desigined to mimic the network of
webpages.  The internet houses many websites that are highly
connected (e.g. Google, Yahoo, etc.) and others that are not.

To generate the network, we will define the process via induction.  A
network of size $1$ is the trivial network.  Given a network of size
$N-1$, attach the additonal $N^{th}$ node to existing node $i \in
\lbrace 1,\ldots,N-1\rbrace$ with probability
#+BEGIN_LaTeX
  \begin{equation*}
    \frac{\sum_{j!=i} A_{j,i}}{\sum_{j,k \;:\; j > k} A_{j,k}}.
  \end{equation*}
#+END_LaTeX

Generating a scale-free network in this fashion results in a
Barabasi-Network.  The defining feature of a scale-free network is the
proportion of nodes with $k$ edges is proportional to $k^{-\gamma}$
for some $\gamma$.  In the case of a Barabasi-Network $\gamma = 3$.

Given the network, we use the Fruchterman-Reingold algorithm to
position the nodes in a two dimensional plane.


#+caption: The scalefree network with 50 locations
#+name: fig:scalefree25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/scalefreeSample.pdf]]




** Covariates

Define $X$ to be a $n \times p$ centered and scaled covariate matrix.
The covariates are multivariate normal $MVN_p(\mu,\Sigma)$ where
$\mu_i = 2\widetilde{C}_{i,1}^2 + 1\widetilde{C}_{i,2}$ and
$\widetilde{C}$ are the centered and scaled coordinates.  The
covariance matrix has the structure $\Sigma_{ip + s, jp + t} =
\rho e^{(-\tau  E_{i,j} - \eta |s-t|)}$.  Thus, the variance of the
individual covariates are $1$ and the correlation decays as $E_{i,j}$
increases and as $|s-t|$ increases.

We need the mass of each individual node to compute the gravity term
in the gravity model.  In the case of White-Nose Syndrome, the mass is
the number of caves.  Arbitrarily set the first covariate to be the
mass of the node.  Define $M_i = \lfloor X_{i,1} - X_{[1],1} \rfloor +
1$ to be the mass of location $i$.


** Network distance

In order for the structure of the network to have a strong impact on
the disease spread, we define distance as the geodesic distance raised
to a power.  The distance between adjacent nodes ($i$ and $j$ such
that $A_{i,j} = 1$) is defined to be $1$.  For non-adjacent nodes, the
distance is the number of edges along the shortest path raised to a
power.  To determine the appropriate power, let $p^{(1)}_{i,j}$ be the
hypothetical probability node $i$ infects node $j$ where $i$ and $j$
have geodesic distance $1$.  Let $p^{(2)}_{i,j}$ be the hypothetical
probability if infection if $i$ and $j$ have geodesic distance $2$.
For their mass, use the mean mass of the network.  The log odds-ratio
is equal to
#+begin_latex
  \begin{equation*}
    - \frac{\alpha}{m^\rho} + \frac{\alpha2^z}{m^\rho}.
  \end{equation*}
#+end_latex
Set this equation equal to $\log(0.5)$ and solve for $z$.


* Simulations



* Results

** Simultaneous perturbation experiment

** Agent jitter and num chunks experiment

** Toy Structures

** WNS
