#+title: M1 Writeup
#+author: 

#+startup: showeverything

#+latex_header: \usepackage{amsmath,amssymb,fullpage,dsfont}
#+latex_header: \newcommand{\bs}{\boldsymbol}
#+latex_header: \newcommand{\attn}[1]{\textbf{***{#1}***}}
#+latex_header: \newcommand{\src}{\attn{source}}
#+latex_header: \setlength{\parskip}{\baselineskip}

* Checklist							   :noexport:
** Notation
   - [ ] Locations
     - [ ] Coordinates
     - [ ] Covariates
     - [ ] Neighbors
   - [ ] Dynamics model
     - [ ] Gravity model
** Structure generation
   - [X] Covariates
   - [ ] Network distance
   - [-] Structures
     - [X] Alley
     - [ ] Bowtie
     - [ ] Grid
     - [X] Random
     - [ ] Ring
     - [ ] Scalefree
** Spread dynamics models
   - [ ] $1 - \Pi_{i}[ 1 - P_{i,j}]$
   - [ ] Gravity model
   - [ ] Range model
   - [ ] Cave model
   - [ ] Setting generative model parameters
** Simulation details
   - [ ] Start settings
   - [ ] Significant points
     - [ ] Model estimation
     - [ ] Strategy estimation
   - [ ] Number of time points
   - [ ] Objective function
   - [ ] Optimization online tuning
   - [ ] Model estimation
** Priority scores
   - [ ] Form of the scores
   - [ ] Selection process
   - [ ] Features
** M1 Optimization
   - [ ] Runners
   - [ ] SGD
** Competing policies
   - [ ] Proximal
   - [ ] Myopic


# begin writing

* Structure generation

** Covariates

Define $X$ to be a $n \times p$ centered and scaled covariate matrix.
The covariates are multivariate normal $MVN_p(\mu,\Sigma)$ where
$\mu_i = 2\widetilde{C}_{i,1}^2 + 1\widetilde{C}_{i,2}$ and
$\widetilde{C}$ are the centered and scaled coordinates.  The
covariance matrix has the structure $\Sigma_{ip + s, jp + t} =
\rho e^{(-\tau  E_{i,j} - \eta |s-t|)}$.  Thus, the variance of the
individual covariates are $1$ and the correlation decays as $E_{i,j}$
increases and as $|s-t|$ increases.

We need the mass of each individual node to compute the gravity term
in the gravity model.  In the case of White-Nose Syndrome, the mass is
the number of caves.  Arbitrarily set the first covariate to be the
mass of the node.  Define $M_i = \lfloor X_{i,1} - X_{[1],1} \rfloor +
1$ to be the mass of location $i$.


** Network distance

In order for the structure of the network to have a strong impact on
the disease spread, we define distance as the geodesic distance raised
to a power.  The distance between adjacent nodes ($i$ and $j$ such
that $A_{i,j} = 1$) is defined to be $1$.  For non-adjacent nodes, the
distance is the number of edges along the shortest path raised to a
power.  To determine the appropriate power, let $p^{(1)}_{i,j}$ be the
hypothetical probability node $i$ infects node $j$ where $i$ and $j$
have geodesic distance $1$.  Let $p^{(2)}_{i,j}$ be the hypothetical
probability if infection if $i$ and $j$ have geodesic distance $2$.
For their mass, use the mean mass of the network.  The log odds-ratio
is equal to
#+begin_latex
  \begin{equation*}
    - \frac{\alpha}{m^\rho} + \frac{\alpha2^z}{m^\rho}.
  \end{equation*}
#+end_latex
Set this equation equal to $\log(0.5)$ and solve for $z$.

** Structures

*** Random Network

The random network generates location coordinates uniformly on $[0,1]
\times [0,1]$.  Let $C$ denote the set of coordinate pairs.  For any
$i \in \lbrace 1,...,n \rbrace$, $C_{i} \in [0,1] \times [0,1]$.

Let $A$ be the $n \times n$ adjacency matrix where $A_{i,j} = 1$ if
locations $i$ and $j$ are adjacent and $A_{i,j} = 0$ otherwise.  To
determine which locations are connected, we must first define some
notation.  Let $E_{i,j} = \|C_{i} - C_{j}\|_2$ and $E_{i,[j]}$ denote
the $j^{th}$ largest norm excluding $E_{i,i}$ which is zero.  The set
of $k$ nearby locations to location $i$ is $N^{(k)}_i = \lbrace j :
E_{i,j} <= E_{i,[k]} \rbrace$.  Now, the adjacency matrix is defined
as $A_{i,j} = 1$ if $i \in N_{j}^{(k)}$ or $j \in N_{i}^{(k)}$.


#+caption: A random network with 25 locations
#+name: fig:rand25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/rand25.pdf]]



*** Starred Alley

The starred alleyway was produced to incorporate the importance of
network centrality metrics.  An example of a starred alleyway can be
found in figure [[fig:alley25]].  By looking at the structure, the goal is
to identify the locations along the main horizontal line.  If these
locations are treated, it helps to contain the spread of the disease.

Distances between nodes are not defined in the usual way.  For any
node on the outer points, the distance to the closest node on the main
horizontal line is $0.9$ instead of $1.0$.

For a starred alley of size $N$, define
#+BEGIN_LaTeX
  \begin{equation*}
    m_N = \underset{m > 0}{\arg\max} \; f(m) \mathds{1}_{\lbrace f(m) \le N
      \rbrace }
  \end{equation*}
#+END_LaTeX
where
# #+BEGIN_LaTeX
#   \begin{equation*}
#     f(m) = m + \left\lceil \frac{m}{2}
#     \right\rceil 
#     \left(\left\lceil \frac{m}{2} \right\rceil - 1\right) 
#     + (2 - (m \text{ mod } 2)) \left\lceil{\frac{m}{2}\right\rceil.
#     \end{equation*}
# #+END_LaTeX
# or simplified, it becomes
#+BEGIN_LaTeX
  \begin{equation*}
    f(m) = m + \left\lceil \frac{m}{2}
    \right\rceil 
    \left(\left\lceil \frac{m}{2} \right\rceil
      - (m \text{ mod } 2) + 1 \right).
  \end{equation*}
#+END_LaTeX

Let locations $1,\ldots,m_N$ index the locations on the main
horizontal line.  Next define disjoint sets of locations
$\mathcal{N}_i$ for $i = 1,\ldots,m_N$.  The cardinality for
$\mathcal{N}_i$ is defined as
#+BEGIN_LaTeX
  \begin{equation*}
    | \mathcal{N}_i | = \left\lfloor \frac{i}{2} \right\rfloor +
    \mathds{1}_{\lbrace(m_N - i) < (N - f(m_N))\rbrace}.
  \end{equation*}
#+END_LaTeX
For each location $j \in \mathcal{N}_i$ set $A_{i,j} = A_{j,i} = 1$.


#+caption: The starred alleyway network with 25 locations
#+name: fig:alley25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/alley25.pdf]]



*** Ring

The ring is a simple circle of locations with a concetrated group in one
section.  To form the ring, place the locations evenly on the circle
then between one pair of locations insert more locations evenly.  An
example can be seen in figure [[fig:ring25]].

#+caption: The ring network with 25 locations
#+name: fig:ring25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/ring25.pdf]]




*** Grid

The grid is a checkerboard-like structure.

#+caption: The grid network with 25 locations
#+name: fig:grid25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/grid25.pdf]]



*** Bowtie

The bowtie combines two grid networks with a random network in
between.  Spread of the disease begins in one grid and travels through
the random network and into the other grid.

#+caption: The bowtie network with 25 locations
#+name: fig:bowtie25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/bowtie25.pdf]]


*** Scalefree

The scalefree network is designed so that some locations are highly
connected while others are only connected by a couple edges.  This
type of network was originally desigined to mimic the network of
webpages.  The internet houses many websites that are highly
connected (e.g. Google, Yahoo, etc.) and others that are not.

To generate the network, we will define the process via induction.  A
network of size $1$ is the trivial network.  Given a network of size
$N-1$, attach the additonal $N^{th}$ node to existing node $i \in
\lbrace 1,\ldots,N-1\rbrace$ with probability
#+BEGIN_LaTeX
  \begin{equation*}
    \frac{\sum_{j!=i} A_{j,i}}{\sum_{j,k \;:\; j > k} A_{j,k}}.
  \end{equation*}
#+END_LaTeX

Generating a scale-free network in this fashion results in a
Barabasi-Network.  The defining feature of a scale-free network is the
proportion of nodes with $k$ edges is proportional to $k^{-\gamma}$
for some $\gamma$.  In the case of a Barabasi-Network $\gamma = 3$.


#+caption: The scalefree network with 25 locations
#+name: fig:scalefree25
#+attr_latex: :width 0.5\textwidth
[[./data/toy/scalefree25.pdf]]
